package com.menzo.menzo.dto.music;

public enum MusicEventType {
    LIVE_MUSIC_SESSION_CREATED,
    LIVE_MUSIC_SEARCH_FAILED,
    LIVE_MUSIC_REQUESTED,
    LIVE_MUSIC_REQUEST_APPROVED,
    LIVE_MUSIC_REQUEST_REJECTED,
    LIVE_MUSIC_QUEUE_UPDATED,
    LIVE_MUSIC_TRACK_ADDED,
    LIVE_MUSIC_STARTED,
    LIVE_MUSIC_PAUSED,
    LIVE_MUSIC_RESUMED,
    LIVE_MUSIC_SEEKED,
    LIVE_MUSIC_SKIPPED,
    LIVE_MUSIC_TRACK_CHANGED,
    LIVE_MUSIC_STOPPED,
    LIVE_MUSIC_SETTINGS_UPDATED,
    LIVE_MUSIC_ERROR
}
